name: Assign Dataverse Role

on:
  workflow_dispatch:
    inputs:
      target_user_upn:
        description: "User principal name (e.g. user@company.com)"
        required: true
        type: string

permissions:
  contents: read

jobs:
  assign-role:
    runs-on: ubuntu-latest

    env:
      TENANT_ID: ${{ secrets.TENANT_ID  }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET  }}
      # ENVIRONMENT_ID: ${{ vars.PP_ENVIRONMENT_ID }}
      # TARGET_ROLE: ${{ vars.PP_TARGET_ROLE }}
      TARGET_USER_UPN: ${{ inputs.target_user_upn }}

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"

      - name: Install PAC CLI
        shell: bash
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool

          echo "$HOME/.dotnet/tools" >> "$GITHUB_PATH"

      - name: Authenticate
        shell: bash
        run: |
          set -euo pipefail

          $HOME/.dotnet/tools/pac auth create \
            --name github-role-job \
            --tenant "$TENANT_ID" \
            --applicationId "$CLIENT_ID" \
            --clientSecret "$CLIENT_SECRET"

          $HOME/.dotnet/tools/pac auth who

      - name: List solutions
        run: |
          $HOME/.dotnet/tools/pac solution list

      - name: Assign Dataverse Role
        shell: bash
        run: |
          set -euo pipefail

          $HOME/.dotnet/tools/pac admin assign-user \
            --environment "c606f688-ad0a-e2fc-bf69-45eeb002a01d" \
            --user "$TARGET_USER_UPN" \
            --role "APIGM"

          echo "Role '$TARGET_ROLE' assigned to '$TARGET_USER_UPN'"
