name: Flow Health Check
 
on:
  workflow_dispatch:
 
jobs:
 
  flow-check:
 
    runs-on: windows-latest
 
    steps:
 
      - uses: actions/checkout@v4
 
      - name: Install PAC
        uses: microsoft/powerplatform-actions/actions-install@v1
 
      - name: Check flows
        shell: pwsh
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          DEV_ENV_URL: ${{ secrets.DEV_ENV_URL }}
        run: |
          ./scripts/Check-PowerAutomateFlows.ps1
