name: Flow Run Check
 
on:
  workflow_dispatch:

env:
  PAC_CLI_VERSION: "2.10.1"
 
jobs:
 
  flow-check:
 
    runs-on: windows-latest
 
    steps:
 
      - uses: actions/checkout@v4
 
      - name: Install PAC CLI ${{ env.PAC_CLI_VERSION }}
        shell: powershell
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool --version $env:PAC_CLI_VERSION
          echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Append
 
      - name: Check flows
        shell: pwsh
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          DEV_ENV_URL: ${{ secrets.DEV_ENV_URL }}
        run: |
          ./scripts/latest-run.ps1
