name: Deploy Solution

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    #runs-on: [self-hosted, Linux, X64]

    steps:

    - name: Checkout PAV Branch
      uses: actions/checkout@v4
      with:
        ref: PowerApps_Versions

    - name: Install Power Platform CLI
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Pack Solution
      uses: microsoft/powerplatform-actions/pack-solution@v1
      with:
        solution-folder: solutions/Pipeline_Test
        solution-file: Pipeline_Test.zip
        solution-type: Managed

    - name: Import Solution
      uses: microsoft/powerplatform-actions/import-solution@v1
      with:
        environment-url: ${{ secrets.TEST_ENV_URL }}
        tenant-id: ${{ secrets.TENANT_ID }}
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        solution-file: Pipeline_Test.zip
        publish-changes: true
