name: DEV to TEST Man Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SOLUTION_NAME: POC_ALM
      DEPLOYMENT_SETTINGS_FILE: settings/test-settings.json

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Power Platform CLI
      uses: microsoft/powerplatform-actions/actions-install@v1

    #################################################
    # EXPORT SOLUTION
    #################################################

    - name: Export Managed Solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{ secrets.DEV_ENV_URL }}
        tenant-id: ${{ secrets.TENANT_ID }}
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        solution-name: ${{ env.SOLUTION_NAME }}
        solution-output-file: unmanaged.zip
        managed: false

    #################################################
    # VERIFY SETTINGS FILE
    #################################################

    - name: Verify Deployment Settings
      run: |
        FILE=${{ env.DEPLOYMENT_SETTINGS_FILE }}

        echo "Checking file: $FILE"

        if [ -f "$FILE" ]; then
          echo ""
          echo "Deployment settings found"
          echo ""
          cat "$FILE"
        else
          echo "Deployment settings file not found"
          exit 1
        fi

    #################################################
    # IMPORT SOLUTION
    #################################################

    - name: Import Solution to TEST
      uses: microsoft/powerplatform-actions/import-solution@v1
      with:
        environment-url: ${{ secrets.TEST_ENV_URL }}
        tenant-id: ${{ secrets.TENANT_ID }}
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        solution-file: unmanaged.zip
        settings-file: ${{ env.DEPLOYMENT_SETTINGS_FILE }}
        publish-changes: true
        use-node-auth: true

    #################################################
    # DEPLOYMENT COMPLETE
    #################################################

    - name: Deployment Complete
      run: |
        echo ""
        echo "======================================="
        echo "Solution deployed successfully"
        echo "Target Environment : PROD"
        echo "Settings File : ${{ env.DEPLOYMENT_SETTINGS_FILE }}"
        echo "======================================="
